// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/onflow/flow-emulator/internal (interfaces: AccessAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/access.go -package=mocks github.com/onflow/flow-emulator/internal AccessAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	access "github.com/onflow/flow/protobuf/go/flow/access"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockAccessAPIClient is a mock of AccessAPIClient interface.
type MockAccessAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAccessAPIClientMockRecorder
	isgomock struct{}
}

// MockAccessAPIClientMockRecorder is the mock recorder for MockAccessAPIClient.
type MockAccessAPIClientMockRecorder struct {
	mock *MockAccessAPIClient
}

// NewMockAccessAPIClient creates a new mock instance.
func NewMockAccessAPIClient(ctrl *gomock.Controller) *MockAccessAPIClient {
	mock := &MockAccessAPIClient{ctrl: ctrl}
	mock.recorder = &MockAccessAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessAPIClient) EXPECT() *MockAccessAPIClientMockRecorder {
	return m.recorder
}

// ExecuteScriptAtBlockHeight mocks base method.
func (m *MockAccessAPIClient) ExecuteScriptAtBlockHeight(ctx context.Context, in *access.ExecuteScriptAtBlockHeightRequest, opts ...grpc.CallOption) (*access.ExecuteScriptResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteScriptAtBlockHeight", varargs...)
	ret0, _ := ret[0].(*access.ExecuteScriptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteScriptAtBlockHeight indicates an expected call of ExecuteScriptAtBlockHeight.
func (mr *MockAccessAPIClientMockRecorder) ExecuteScriptAtBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScriptAtBlockHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).ExecuteScriptAtBlockHeight), varargs...)
}

// ExecuteScriptAtBlockID mocks base method.
func (m *MockAccessAPIClient) ExecuteScriptAtBlockID(ctx context.Context, in *access.ExecuteScriptAtBlockIDRequest, opts ...grpc.CallOption) (*access.ExecuteScriptResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteScriptAtBlockID", varargs...)
	ret0, _ := ret[0].(*access.ExecuteScriptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteScriptAtBlockID indicates an expected call of ExecuteScriptAtBlockID.
func (mr *MockAccessAPIClientMockRecorder) ExecuteScriptAtBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScriptAtBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).ExecuteScriptAtBlockID), varargs...)
}

// ExecuteScriptAtLatestBlock mocks base method.
func (m *MockAccessAPIClient) ExecuteScriptAtLatestBlock(ctx context.Context, in *access.ExecuteScriptAtLatestBlockRequest, opts ...grpc.CallOption) (*access.ExecuteScriptResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecuteScriptAtLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.ExecuteScriptResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteScriptAtLatestBlock indicates an expected call of ExecuteScriptAtLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) ExecuteScriptAtLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteScriptAtLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).ExecuteScriptAtLatestBlock), varargs...)
}

// GetAccount mocks base method.
func (m *MockAccessAPIClient) GetAccount(ctx context.Context, in *access.GetAccountRequest, opts ...grpc.CallOption) (*access.GetAccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccount", varargs...)
	ret0, _ := ret[0].(*access.GetAccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockAccessAPIClientMockRecorder) GetAccount(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccount), varargs...)
}

// GetAccountAtBlockHeight mocks base method.
func (m *MockAccessAPIClient) GetAccountAtBlockHeight(ctx context.Context, in *access.GetAccountAtBlockHeightRequest, opts ...grpc.CallOption) (*access.AccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountAtBlockHeight", varargs...)
	ret0, _ := ret[0].(*access.AccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountAtBlockHeight indicates an expected call of GetAccountAtBlockHeight.
func (mr *MockAccessAPIClientMockRecorder) GetAccountAtBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountAtBlockHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountAtBlockHeight), varargs...)
}

// GetAccountAtLatestBlock mocks base method.
func (m *MockAccessAPIClient) GetAccountAtLatestBlock(ctx context.Context, in *access.GetAccountAtLatestBlockRequest, opts ...grpc.CallOption) (*access.AccountResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountAtLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.AccountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountAtLatestBlock indicates an expected call of GetAccountAtLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) GetAccountAtLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountAtLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountAtLatestBlock), varargs...)
}

// GetAccountBalanceAtBlockHeight mocks base method.
func (m *MockAccessAPIClient) GetAccountBalanceAtBlockHeight(ctx context.Context, in *access.GetAccountBalanceAtBlockHeightRequest, opts ...grpc.CallOption) (*access.AccountBalanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountBalanceAtBlockHeight", varargs...)
	ret0, _ := ret[0].(*access.AccountBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalanceAtBlockHeight indicates an expected call of GetAccountBalanceAtBlockHeight.
func (mr *MockAccessAPIClientMockRecorder) GetAccountBalanceAtBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalanceAtBlockHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountBalanceAtBlockHeight), varargs...)
}

// GetAccountBalanceAtLatestBlock mocks base method.
func (m *MockAccessAPIClient) GetAccountBalanceAtLatestBlock(ctx context.Context, in *access.GetAccountBalanceAtLatestBlockRequest, opts ...grpc.CallOption) (*access.AccountBalanceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountBalanceAtLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.AccountBalanceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalanceAtLatestBlock indicates an expected call of GetAccountBalanceAtLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) GetAccountBalanceAtLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalanceAtLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountBalanceAtLatestBlock), varargs...)
}

// GetAccountKeyAtBlockHeight mocks base method.
func (m *MockAccessAPIClient) GetAccountKeyAtBlockHeight(ctx context.Context, in *access.GetAccountKeyAtBlockHeightRequest, opts ...grpc.CallOption) (*access.AccountKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountKeyAtBlockHeight", varargs...)
	ret0, _ := ret[0].(*access.AccountKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountKeyAtBlockHeight indicates an expected call of GetAccountKeyAtBlockHeight.
func (mr *MockAccessAPIClientMockRecorder) GetAccountKeyAtBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountKeyAtBlockHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountKeyAtBlockHeight), varargs...)
}

// GetAccountKeyAtLatestBlock mocks base method.
func (m *MockAccessAPIClient) GetAccountKeyAtLatestBlock(ctx context.Context, in *access.GetAccountKeyAtLatestBlockRequest, opts ...grpc.CallOption) (*access.AccountKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountKeyAtLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.AccountKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountKeyAtLatestBlock indicates an expected call of GetAccountKeyAtLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) GetAccountKeyAtLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountKeyAtLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountKeyAtLatestBlock), varargs...)
}

// GetAccountKeysAtBlockHeight mocks base method.
func (m *MockAccessAPIClient) GetAccountKeysAtBlockHeight(ctx context.Context, in *access.GetAccountKeysAtBlockHeightRequest, opts ...grpc.CallOption) (*access.AccountKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountKeysAtBlockHeight", varargs...)
	ret0, _ := ret[0].(*access.AccountKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountKeysAtBlockHeight indicates an expected call of GetAccountKeysAtBlockHeight.
func (mr *MockAccessAPIClientMockRecorder) GetAccountKeysAtBlockHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountKeysAtBlockHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountKeysAtBlockHeight), varargs...)
}

// GetAccountKeysAtLatestBlock mocks base method.
func (m *MockAccessAPIClient) GetAccountKeysAtLatestBlock(ctx context.Context, in *access.GetAccountKeysAtLatestBlockRequest, opts ...grpc.CallOption) (*access.AccountKeysResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAccountKeysAtLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.AccountKeysResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountKeysAtLatestBlock indicates an expected call of GetAccountKeysAtLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) GetAccountKeysAtLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountKeysAtLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).GetAccountKeysAtLatestBlock), varargs...)
}

// GetBlockByHeight mocks base method.
func (m *MockAccessAPIClient) GetBlockByHeight(ctx context.Context, in *access.GetBlockByHeightRequest, opts ...grpc.CallOption) (*access.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockByHeight", varargs...)
	ret0, _ := ret[0].(*access.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHeight indicates an expected call of GetBlockByHeight.
func (mr *MockAccessAPIClientMockRecorder) GetBlockByHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetBlockByHeight), varargs...)
}

// GetBlockByID mocks base method.
func (m *MockAccessAPIClient) GetBlockByID(ctx context.Context, in *access.GetBlockByIDRequest, opts ...grpc.CallOption) (*access.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockByID", varargs...)
	ret0, _ := ret[0].(*access.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByID indicates an expected call of GetBlockByID.
func (mr *MockAccessAPIClientMockRecorder) GetBlockByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetBlockByID), varargs...)
}

// GetBlockHeaderByHeight mocks base method.
func (m *MockAccessAPIClient) GetBlockHeaderByHeight(ctx context.Context, in *access.GetBlockHeaderByHeightRequest, opts ...grpc.CallOption) (*access.BlockHeaderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockHeaderByHeight", varargs...)
	ret0, _ := ret[0].(*access.BlockHeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHeaderByHeight indicates an expected call of GetBlockHeaderByHeight.
func (mr *MockAccessAPIClientMockRecorder) GetBlockHeaderByHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHeaderByHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetBlockHeaderByHeight), varargs...)
}

// GetBlockHeaderByID mocks base method.
func (m *MockAccessAPIClient) GetBlockHeaderByID(ctx context.Context, in *access.GetBlockHeaderByIDRequest, opts ...grpc.CallOption) (*access.BlockHeaderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBlockHeaderByID", varargs...)
	ret0, _ := ret[0].(*access.BlockHeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockHeaderByID indicates an expected call of GetBlockHeaderByID.
func (mr *MockAccessAPIClientMockRecorder) GetBlockHeaderByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockHeaderByID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetBlockHeaderByID), varargs...)
}

// GetCollectionByID mocks base method.
func (m *MockAccessAPIClient) GetCollectionByID(ctx context.Context, in *access.GetCollectionByIDRequest, opts ...grpc.CallOption) (*access.CollectionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCollectionByID", varargs...)
	ret0, _ := ret[0].(*access.CollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCollectionByID indicates an expected call of GetCollectionByID.
func (mr *MockAccessAPIClientMockRecorder) GetCollectionByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCollectionByID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetCollectionByID), varargs...)
}

// GetEventsForBlockIDs mocks base method.
func (m *MockAccessAPIClient) GetEventsForBlockIDs(ctx context.Context, in *access.GetEventsForBlockIDsRequest, opts ...grpc.CallOption) (*access.EventsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEventsForBlockIDs", varargs...)
	ret0, _ := ret[0].(*access.EventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForBlockIDs indicates an expected call of GetEventsForBlockIDs.
func (mr *MockAccessAPIClientMockRecorder) GetEventsForBlockIDs(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForBlockIDs", reflect.TypeOf((*MockAccessAPIClient)(nil).GetEventsForBlockIDs), varargs...)
}

// GetEventsForHeightRange mocks base method.
func (m *MockAccessAPIClient) GetEventsForHeightRange(ctx context.Context, in *access.GetEventsForHeightRangeRequest, opts ...grpc.CallOption) (*access.EventsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetEventsForHeightRange", varargs...)
	ret0, _ := ret[0].(*access.EventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsForHeightRange indicates an expected call of GetEventsForHeightRange.
func (mr *MockAccessAPIClientMockRecorder) GetEventsForHeightRange(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsForHeightRange", reflect.TypeOf((*MockAccessAPIClient)(nil).GetEventsForHeightRange), varargs...)
}

// GetExecutionResultByID mocks base method.
func (m *MockAccessAPIClient) GetExecutionResultByID(ctx context.Context, in *access.GetExecutionResultByIDRequest, opts ...grpc.CallOption) (*access.ExecutionResultByIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetExecutionResultByID", varargs...)
	ret0, _ := ret[0].(*access.ExecutionResultByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionResultByID indicates an expected call of GetExecutionResultByID.
func (mr *MockAccessAPIClientMockRecorder) GetExecutionResultByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionResultByID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetExecutionResultByID), varargs...)
}

// GetExecutionResultForBlockID mocks base method.
func (m *MockAccessAPIClient) GetExecutionResultForBlockID(ctx context.Context, in *access.GetExecutionResultForBlockIDRequest, opts ...grpc.CallOption) (*access.ExecutionResultForBlockIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetExecutionResultForBlockID", varargs...)
	ret0, _ := ret[0].(*access.ExecutionResultForBlockIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionResultForBlockID indicates an expected call of GetExecutionResultForBlockID.
func (mr *MockAccessAPIClientMockRecorder) GetExecutionResultForBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionResultForBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetExecutionResultForBlockID), varargs...)
}

// GetFullCollectionByID mocks base method.
func (m *MockAccessAPIClient) GetFullCollectionByID(ctx context.Context, in *access.GetFullCollectionByIDRequest, opts ...grpc.CallOption) (*access.FullCollectionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFullCollectionByID", varargs...)
	ret0, _ := ret[0].(*access.FullCollectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullCollectionByID indicates an expected call of GetFullCollectionByID.
func (mr *MockAccessAPIClientMockRecorder) GetFullCollectionByID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullCollectionByID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetFullCollectionByID), varargs...)
}

// GetLatestBlock mocks base method.
func (m *MockAccessAPIClient) GetLatestBlock(ctx context.Context, in *access.GetLatestBlockRequest, opts ...grpc.CallOption) (*access.BlockResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLatestBlock", varargs...)
	ret0, _ := ret[0].(*access.BlockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlock indicates an expected call of GetLatestBlock.
func (mr *MockAccessAPIClientMockRecorder) GetLatestBlock(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlock", reflect.TypeOf((*MockAccessAPIClient)(nil).GetLatestBlock), varargs...)
}

// GetLatestBlockHeader mocks base method.
func (m *MockAccessAPIClient) GetLatestBlockHeader(ctx context.Context, in *access.GetLatestBlockHeaderRequest, opts ...grpc.CallOption) (*access.BlockHeaderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLatestBlockHeader", varargs...)
	ret0, _ := ret[0].(*access.BlockHeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlockHeader indicates an expected call of GetLatestBlockHeader.
func (mr *MockAccessAPIClientMockRecorder) GetLatestBlockHeader(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlockHeader", reflect.TypeOf((*MockAccessAPIClient)(nil).GetLatestBlockHeader), varargs...)
}

// GetLatestProtocolStateSnapshot mocks base method.
func (m *MockAccessAPIClient) GetLatestProtocolStateSnapshot(ctx context.Context, in *access.GetLatestProtocolStateSnapshotRequest, opts ...grpc.CallOption) (*access.ProtocolStateSnapshotResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLatestProtocolStateSnapshot", varargs...)
	ret0, _ := ret[0].(*access.ProtocolStateSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestProtocolStateSnapshot indicates an expected call of GetLatestProtocolStateSnapshot.
func (mr *MockAccessAPIClientMockRecorder) GetLatestProtocolStateSnapshot(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestProtocolStateSnapshot", reflect.TypeOf((*MockAccessAPIClient)(nil).GetLatestProtocolStateSnapshot), varargs...)
}

// GetNetworkParameters mocks base method.
func (m *MockAccessAPIClient) GetNetworkParameters(ctx context.Context, in *access.GetNetworkParametersRequest, opts ...grpc.CallOption) (*access.GetNetworkParametersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNetworkParameters", varargs...)
	ret0, _ := ret[0].(*access.GetNetworkParametersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNetworkParameters indicates an expected call of GetNetworkParameters.
func (mr *MockAccessAPIClientMockRecorder) GetNetworkParameters(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNetworkParameters", reflect.TypeOf((*MockAccessAPIClient)(nil).GetNetworkParameters), varargs...)
}

// GetNodeVersionInfo mocks base method.
func (m *MockAccessAPIClient) GetNodeVersionInfo(ctx context.Context, in *access.GetNodeVersionInfoRequest, opts ...grpc.CallOption) (*access.GetNodeVersionInfoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNodeVersionInfo", varargs...)
	ret0, _ := ret[0].(*access.GetNodeVersionInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeVersionInfo indicates an expected call of GetNodeVersionInfo.
func (mr *MockAccessAPIClientMockRecorder) GetNodeVersionInfo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeVersionInfo", reflect.TypeOf((*MockAccessAPIClient)(nil).GetNodeVersionInfo), varargs...)
}

// GetProtocolStateSnapshotByBlockID mocks base method.
func (m *MockAccessAPIClient) GetProtocolStateSnapshotByBlockID(ctx context.Context, in *access.GetProtocolStateSnapshotByBlockIDRequest, opts ...grpc.CallOption) (*access.ProtocolStateSnapshotResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProtocolStateSnapshotByBlockID", varargs...)
	ret0, _ := ret[0].(*access.ProtocolStateSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProtocolStateSnapshotByBlockID indicates an expected call of GetProtocolStateSnapshotByBlockID.
func (mr *MockAccessAPIClientMockRecorder) GetProtocolStateSnapshotByBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtocolStateSnapshotByBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetProtocolStateSnapshotByBlockID), varargs...)
}

// GetProtocolStateSnapshotByHeight mocks base method.
func (m *MockAccessAPIClient) GetProtocolStateSnapshotByHeight(ctx context.Context, in *access.GetProtocolStateSnapshotByHeightRequest, opts ...grpc.CallOption) (*access.ProtocolStateSnapshotResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProtocolStateSnapshotByHeight", varargs...)
	ret0, _ := ret[0].(*access.ProtocolStateSnapshotResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProtocolStateSnapshotByHeight indicates an expected call of GetProtocolStateSnapshotByHeight.
func (mr *MockAccessAPIClientMockRecorder) GetProtocolStateSnapshotByHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProtocolStateSnapshotByHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).GetProtocolStateSnapshotByHeight), varargs...)
}

// GetScheduledTransaction mocks base method.
func (m *MockAccessAPIClient) GetScheduledTransaction(ctx context.Context, in *access.GetScheduledTransactionRequest, opts ...grpc.CallOption) (*access.TransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetScheduledTransaction", varargs...)
	ret0, _ := ret[0].(*access.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledTransaction indicates an expected call of GetScheduledTransaction.
func (mr *MockAccessAPIClientMockRecorder) GetScheduledTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledTransaction", reflect.TypeOf((*MockAccessAPIClient)(nil).GetScheduledTransaction), varargs...)
}

// GetScheduledTransactionResult mocks base method.
func (m *MockAccessAPIClient) GetScheduledTransactionResult(ctx context.Context, in *access.GetScheduledTransactionResultRequest, opts ...grpc.CallOption) (*access.TransactionResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetScheduledTransactionResult", varargs...)
	ret0, _ := ret[0].(*access.TransactionResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScheduledTransactionResult indicates an expected call of GetScheduledTransactionResult.
func (mr *MockAccessAPIClientMockRecorder) GetScheduledTransactionResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScheduledTransactionResult", reflect.TypeOf((*MockAccessAPIClient)(nil).GetScheduledTransactionResult), varargs...)
}

// GetSystemTransaction mocks base method.
func (m *MockAccessAPIClient) GetSystemTransaction(ctx context.Context, in *access.GetSystemTransactionRequest, opts ...grpc.CallOption) (*access.TransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSystemTransaction", varargs...)
	ret0, _ := ret[0].(*access.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemTransaction indicates an expected call of GetSystemTransaction.
func (mr *MockAccessAPIClientMockRecorder) GetSystemTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemTransaction", reflect.TypeOf((*MockAccessAPIClient)(nil).GetSystemTransaction), varargs...)
}

// GetSystemTransactionResult mocks base method.
func (m *MockAccessAPIClient) GetSystemTransactionResult(ctx context.Context, in *access.GetSystemTransactionResultRequest, opts ...grpc.CallOption) (*access.TransactionResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSystemTransactionResult", varargs...)
	ret0, _ := ret[0].(*access.TransactionResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemTransactionResult indicates an expected call of GetSystemTransactionResult.
func (mr *MockAccessAPIClientMockRecorder) GetSystemTransactionResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemTransactionResult", reflect.TypeOf((*MockAccessAPIClient)(nil).GetSystemTransactionResult), varargs...)
}

// GetTransaction mocks base method.
func (m *MockAccessAPIClient) GetTransaction(ctx context.Context, in *access.GetTransactionRequest, opts ...grpc.CallOption) (*access.TransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransaction", varargs...)
	ret0, _ := ret[0].(*access.TransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockAccessAPIClientMockRecorder) GetTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockAccessAPIClient)(nil).GetTransaction), varargs...)
}

// GetTransactionResult mocks base method.
func (m *MockAccessAPIClient) GetTransactionResult(ctx context.Context, in *access.GetTransactionRequest, opts ...grpc.CallOption) (*access.TransactionResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionResult", varargs...)
	ret0, _ := ret[0].(*access.TransactionResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionResult indicates an expected call of GetTransactionResult.
func (mr *MockAccessAPIClientMockRecorder) GetTransactionResult(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionResult", reflect.TypeOf((*MockAccessAPIClient)(nil).GetTransactionResult), varargs...)
}

// GetTransactionResultByIndex mocks base method.
func (m *MockAccessAPIClient) GetTransactionResultByIndex(ctx context.Context, in *access.GetTransactionByIndexRequest, opts ...grpc.CallOption) (*access.TransactionResultResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionResultByIndex", varargs...)
	ret0, _ := ret[0].(*access.TransactionResultResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionResultByIndex indicates an expected call of GetTransactionResultByIndex.
func (mr *MockAccessAPIClientMockRecorder) GetTransactionResultByIndex(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionResultByIndex", reflect.TypeOf((*MockAccessAPIClient)(nil).GetTransactionResultByIndex), varargs...)
}

// GetTransactionResultsByBlockID mocks base method.
func (m *MockAccessAPIClient) GetTransactionResultsByBlockID(ctx context.Context, in *access.GetTransactionsByBlockIDRequest, opts ...grpc.CallOption) (*access.TransactionResultsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionResultsByBlockID", varargs...)
	ret0, _ := ret[0].(*access.TransactionResultsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionResultsByBlockID indicates an expected call of GetTransactionResultsByBlockID.
func (mr *MockAccessAPIClientMockRecorder) GetTransactionResultsByBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionResultsByBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetTransactionResultsByBlockID), varargs...)
}

// GetTransactionsByBlockID mocks base method.
func (m *MockAccessAPIClient) GetTransactionsByBlockID(ctx context.Context, in *access.GetTransactionsByBlockIDRequest, opts ...grpc.CallOption) (*access.TransactionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTransactionsByBlockID", varargs...)
	ret0, _ := ret[0].(*access.TransactionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByBlockID indicates an expected call of GetTransactionsByBlockID.
func (mr *MockAccessAPIClientMockRecorder) GetTransactionsByBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).GetTransactionsByBlockID), varargs...)
}

// Ping mocks base method.
func (m *MockAccessAPIClient) Ping(ctx context.Context, in *access.PingRequest, opts ...grpc.CallOption) (*access.PingResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Ping", varargs...)
	ret0, _ := ret[0].(*access.PingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ping indicates an expected call of Ping.
func (mr *MockAccessAPIClientMockRecorder) Ping(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAccessAPIClient)(nil).Ping), varargs...)
}

// SendAndSubscribeTransactionStatuses mocks base method.
func (m *MockAccessAPIClient) SendAndSubscribeTransactionStatuses(ctx context.Context, in *access.SendAndSubscribeTransactionStatusesRequest, opts ...grpc.CallOption) (access.AccessAPI_SendAndSubscribeTransactionStatusesClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendAndSubscribeTransactionStatuses", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SendAndSubscribeTransactionStatusesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendAndSubscribeTransactionStatuses indicates an expected call of SendAndSubscribeTransactionStatuses.
func (mr *MockAccessAPIClientMockRecorder) SendAndSubscribeTransactionStatuses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndSubscribeTransactionStatuses", reflect.TypeOf((*MockAccessAPIClient)(nil).SendAndSubscribeTransactionStatuses), varargs...)
}

// SendTransaction mocks base method.
func (m *MockAccessAPIClient) SendTransaction(ctx context.Context, in *access.SendTransactionRequest, opts ...grpc.CallOption) (*access.SendTransactionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SendTransaction", varargs...)
	ret0, _ := ret[0].(*access.SendTransactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendTransaction indicates an expected call of SendTransaction.
func (mr *MockAccessAPIClientMockRecorder) SendTransaction(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTransaction", reflect.TypeOf((*MockAccessAPIClient)(nil).SendTransaction), varargs...)
}

// SubscribeBlockDigestsFromLatest mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockDigestsFromLatest(ctx context.Context, in *access.SubscribeBlockDigestsFromLatestRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockDigestsFromLatestClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockDigestsFromLatest", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockDigestsFromLatestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockDigestsFromLatest indicates an expected call of SubscribeBlockDigestsFromLatest.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockDigestsFromLatest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockDigestsFromLatest", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockDigestsFromLatest), varargs...)
}

// SubscribeBlockDigestsFromStartBlockID mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockDigestsFromStartBlockID(ctx context.Context, in *access.SubscribeBlockDigestsFromStartBlockIDRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockDigestsFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockDigestsFromStartBlockID", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockDigestsFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockDigestsFromStartBlockID indicates an expected call of SubscribeBlockDigestsFromStartBlockID.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockDigestsFromStartBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockDigestsFromStartBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockDigestsFromStartBlockID), varargs...)
}

// SubscribeBlockDigestsFromStartHeight mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockDigestsFromStartHeight(ctx context.Context, in *access.SubscribeBlockDigestsFromStartHeightRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockDigestsFromStartHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockDigestsFromStartHeight", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockDigestsFromStartHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockDigestsFromStartHeight indicates an expected call of SubscribeBlockDigestsFromStartHeight.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockDigestsFromStartHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockDigestsFromStartHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockDigestsFromStartHeight), varargs...)
}

// SubscribeBlockHeadersFromLatest mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockHeadersFromLatest(ctx context.Context, in *access.SubscribeBlockHeadersFromLatestRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockHeadersFromLatestClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockHeadersFromLatest", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockHeadersFromLatestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockHeadersFromLatest indicates an expected call of SubscribeBlockHeadersFromLatest.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockHeadersFromLatest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockHeadersFromLatest", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockHeadersFromLatest), varargs...)
}

// SubscribeBlockHeadersFromStartBlockID mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockHeadersFromStartBlockID(ctx context.Context, in *access.SubscribeBlockHeadersFromStartBlockIDRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockHeadersFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockHeadersFromStartBlockID", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockHeadersFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockHeadersFromStartBlockID indicates an expected call of SubscribeBlockHeadersFromStartBlockID.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockHeadersFromStartBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockHeadersFromStartBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockHeadersFromStartBlockID), varargs...)
}

// SubscribeBlockHeadersFromStartHeight mocks base method.
func (m *MockAccessAPIClient) SubscribeBlockHeadersFromStartHeight(ctx context.Context, in *access.SubscribeBlockHeadersFromStartHeightRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlockHeadersFromStartHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlockHeadersFromStartHeight", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlockHeadersFromStartHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlockHeadersFromStartHeight indicates an expected call of SubscribeBlockHeadersFromStartHeight.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlockHeadersFromStartHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlockHeadersFromStartHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlockHeadersFromStartHeight), varargs...)
}

// SubscribeBlocksFromLatest mocks base method.
func (m *MockAccessAPIClient) SubscribeBlocksFromLatest(ctx context.Context, in *access.SubscribeBlocksFromLatestRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlocksFromLatestClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlocksFromLatest", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlocksFromLatestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlocksFromLatest indicates an expected call of SubscribeBlocksFromLatest.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlocksFromLatest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlocksFromLatest", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlocksFromLatest), varargs...)
}

// SubscribeBlocksFromStartBlockID mocks base method.
func (m *MockAccessAPIClient) SubscribeBlocksFromStartBlockID(ctx context.Context, in *access.SubscribeBlocksFromStartBlockIDRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlocksFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlocksFromStartBlockID", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlocksFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlocksFromStartBlockID indicates an expected call of SubscribeBlocksFromStartBlockID.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlocksFromStartBlockID(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlocksFromStartBlockID", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlocksFromStartBlockID), varargs...)
}

// SubscribeBlocksFromStartHeight mocks base method.
func (m *MockAccessAPIClient) SubscribeBlocksFromStartHeight(ctx context.Context, in *access.SubscribeBlocksFromStartHeightRequest, opts ...grpc.CallOption) (access.AccessAPI_SubscribeBlocksFromStartHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeBlocksFromStartHeight", varargs...)
	ret0, _ := ret[0].(access.AccessAPI_SubscribeBlocksFromStartHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeBlocksFromStartHeight indicates an expected call of SubscribeBlocksFromStartHeight.
func (mr *MockAccessAPIClientMockRecorder) SubscribeBlocksFromStartHeight(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeBlocksFromStartHeight", reflect.TypeOf((*MockAccessAPIClient)(nil).SubscribeBlocksFromStartHeight), varargs...)
}
