// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/onflow/flow-emulator/internal (interfaces: ExecutionDataAPIClient)
//
// Generated by this command:
//
//	mockgen -destination=internal/mocks/executiondata.go -package=mocks github.com/onflow/flow-emulator/internal ExecutionDataAPIClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	executiondata "github.com/onflow/flow/protobuf/go/flow/executiondata"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockExecutionDataAPIClient is a mock of ExecutionDataAPIClient interface.
type MockExecutionDataAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockExecutionDataAPIClientMockRecorder
}

// MockExecutionDataAPIClientMockRecorder is the mock recorder for MockExecutionDataAPIClient.
type MockExecutionDataAPIClientMockRecorder struct {
	mock *MockExecutionDataAPIClient
}

// NewMockExecutionDataAPIClient creates a new mock instance.
func NewMockExecutionDataAPIClient(ctrl *gomock.Controller) *MockExecutionDataAPIClient {
	mock := &MockExecutionDataAPIClient{ctrl: ctrl}
	mock.recorder = &MockExecutionDataAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutionDataAPIClient) EXPECT() *MockExecutionDataAPIClientMockRecorder {
	return m.recorder
}

// GetExecutionDataByBlockID mocks base method.
func (m *MockExecutionDataAPIClient) GetExecutionDataByBlockID(arg0 context.Context, arg1 *executiondata.GetExecutionDataByBlockIDRequest, arg2 ...grpc.CallOption) (*executiondata.GetExecutionDataByBlockIDResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetExecutionDataByBlockID", varargs...)
	ret0, _ := ret[0].(*executiondata.GetExecutionDataByBlockIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExecutionDataByBlockID indicates an expected call of GetExecutionDataByBlockID.
func (mr *MockExecutionDataAPIClientMockRecorder) GetExecutionDataByBlockID(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionDataByBlockID", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).GetExecutionDataByBlockID), varargs...)
}

// GetRegisterValues mocks base method.
func (m *MockExecutionDataAPIClient) GetRegisterValues(arg0 context.Context, arg1 *executiondata.GetRegisterValuesRequest, arg2 ...grpc.CallOption) (*executiondata.GetRegisterValuesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetRegisterValues", varargs...)
	ret0, _ := ret[0].(*executiondata.GetRegisterValuesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegisterValues indicates an expected call of GetRegisterValues.
func (mr *MockExecutionDataAPIClientMockRecorder) GetRegisterValues(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegisterValues", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).GetRegisterValues), varargs...)
}

// SubscribeAccountStatusesFromLatestBlock mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeAccountStatusesFromLatestBlock(arg0 context.Context, arg1 *executiondata.SubscribeAccountStatusesFromLatestBlockRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromLatestBlockClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeAccountStatusesFromLatestBlock", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromLatestBlockClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeAccountStatusesFromLatestBlock indicates an expected call of SubscribeAccountStatusesFromLatestBlock.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeAccountStatusesFromLatestBlock(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAccountStatusesFromLatestBlock", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeAccountStatusesFromLatestBlock), varargs...)
}

// SubscribeAccountStatusesFromStartBlockID mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeAccountStatusesFromStartBlockID(arg0 context.Context, arg1 *executiondata.SubscribeAccountStatusesFromStartBlockIDRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeAccountStatusesFromStartBlockID", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeAccountStatusesFromStartBlockID indicates an expected call of SubscribeAccountStatusesFromStartBlockID.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeAccountStatusesFromStartBlockID(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAccountStatusesFromStartBlockID", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeAccountStatusesFromStartBlockID), varargs...)
}

// SubscribeAccountStatusesFromStartHeight mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeAccountStatusesFromStartHeight(arg0 context.Context, arg1 *executiondata.SubscribeAccountStatusesFromStartHeightRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromStartHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeAccountStatusesFromStartHeight", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeAccountStatusesFromStartHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeAccountStatusesFromStartHeight indicates an expected call of SubscribeAccountStatusesFromStartHeight.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeAccountStatusesFromStartHeight(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAccountStatusesFromStartHeight", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeAccountStatusesFromStartHeight), varargs...)
}

// SubscribeEvents mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeEvents(arg0 context.Context, arg1 *executiondata.SubscribeEventsRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeEventsClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeEvents", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeEventsClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEvents indicates an expected call of SubscribeEvents.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeEvents(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEvents", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeEvents), varargs...)
}

// SubscribeEventsFromLatest mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeEventsFromLatest(arg0 context.Context, arg1 *executiondata.SubscribeEventsFromLatestRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeEventsFromLatestClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeEventsFromLatest", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeEventsFromLatestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEventsFromLatest indicates an expected call of SubscribeEventsFromLatest.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeEventsFromLatest(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEventsFromLatest", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeEventsFromLatest), varargs...)
}

// SubscribeEventsFromStartBlockID mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeEventsFromStartBlockID(arg0 context.Context, arg1 *executiondata.SubscribeEventsFromStartBlockIDRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeEventsFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeEventsFromStartBlockID", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeEventsFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEventsFromStartBlockID indicates an expected call of SubscribeEventsFromStartBlockID.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeEventsFromStartBlockID(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEventsFromStartBlockID", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeEventsFromStartBlockID), varargs...)
}

// SubscribeEventsFromStartHeight mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeEventsFromStartHeight(arg0 context.Context, arg1 *executiondata.SubscribeEventsFromStartHeightRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeEventsFromStartHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeEventsFromStartHeight", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeEventsFromStartHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeEventsFromStartHeight indicates an expected call of SubscribeEventsFromStartHeight.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeEventsFromStartHeight(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeEventsFromStartHeight", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeEventsFromStartHeight), varargs...)
}

// SubscribeExecutionData mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeExecutionData(arg0 context.Context, arg1 *executiondata.SubscribeExecutionDataRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeExecutionDataClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeExecutionData", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeExecutionDataClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExecutionData indicates an expected call of SubscribeExecutionData.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeExecutionData(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExecutionData", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeExecutionData), varargs...)
}

// SubscribeExecutionDataFromLatest mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeExecutionDataFromLatest(arg0 context.Context, arg1 *executiondata.SubscribeExecutionDataFromLatestRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeExecutionDataFromLatestClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeExecutionDataFromLatest", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeExecutionDataFromLatestClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExecutionDataFromLatest indicates an expected call of SubscribeExecutionDataFromLatest.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeExecutionDataFromLatest(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExecutionDataFromLatest", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeExecutionDataFromLatest), varargs...)
}

// SubscribeExecutionDataFromStartBlockHeight mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeExecutionDataFromStartBlockHeight(arg0 context.Context, arg1 *executiondata.SubscribeExecutionDataFromStartBlockHeightRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeExecutionDataFromStartBlockHeightClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeExecutionDataFromStartBlockHeight", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeExecutionDataFromStartBlockHeightClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExecutionDataFromStartBlockHeight indicates an expected call of SubscribeExecutionDataFromStartBlockHeight.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeExecutionDataFromStartBlockHeight(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExecutionDataFromStartBlockHeight", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeExecutionDataFromStartBlockHeight), varargs...)
}

// SubscribeExecutionDataFromStartBlockID mocks base method.
func (m *MockExecutionDataAPIClient) SubscribeExecutionDataFromStartBlockID(arg0 context.Context, arg1 *executiondata.SubscribeExecutionDataFromStartBlockIDRequest, arg2 ...grpc.CallOption) (executiondata.ExecutionDataAPI_SubscribeExecutionDataFromStartBlockIDClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeExecutionDataFromStartBlockID", varargs...)
	ret0, _ := ret[0].(executiondata.ExecutionDataAPI_SubscribeExecutionDataFromStartBlockIDClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeExecutionDataFromStartBlockID indicates an expected call of SubscribeExecutionDataFromStartBlockID.
func (mr *MockExecutionDataAPIClientMockRecorder) SubscribeExecutionDataFromStartBlockID(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeExecutionDataFromStartBlockID", reflect.TypeOf((*MockExecutionDataAPIClient)(nil).SubscribeExecutionDataFromStartBlockID), varargs...)
}
