- color: 3E4B9E
  description: ""
  name: Epic
- color: 0e8a16
  description: A new user feature or a new package API
  name: Feature
- color: d4c5f9
  description: ""
  name: Feedback
- color: 1d76db
  description: Technical work without new features, refactoring, improving tests
  name: Improvement
- color: d73a4a
  description: The issue represents a bug, malfunction, regression
  name: Bug
- color: 0075ca
  description: The issue in documentation, missing docs, invalid docs, outdated docs
  name: Documentation
- color: c2e0c6
  description: A feature we want the help from community
  name: Help wanted
- color: cccccc
  description: The issue was not well defined, waiting for more information from the submittor
  name: Needs information
